[project]
name = "docker-image-pusher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "prettytable>=3.16.0",
    "pyyaml>=6.0.2",
    "typer>=0.15.2",
]
